#!/bin/bash

# if ! ps -aux | grep -v grep | grep "polybar monitor1"; then
  killall polybar
  polybar monitor1
# fi

# if ! ps -aux | grep -v grep | grep "glava --desktop"; then
  #killall glava
  #glava --desktop
# fi
